#!/bin/bash
# Created by Amirhossein Taran
# Dec 28 2024

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

runApplication blockMesh
runApplication setAlphaField
runApplication decomposePar
runParallel interDielectricFoam
